### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of null

### ISSUE THREAD

**Issue by cfey** [nitin42/react-perf-devtool#40]
Hi, when I follow your install instructions and open the inspector tab I get the following error:
```
Uncaught TypeError: Cannot read property 'length' of null
    at Object.acquireContext (VM37 Chart.js:12635)
    at Chart.construct (VM37 Chart.js:4608)
    at new Chart (VM37 Chart.js:7234)
    at t.drawChart (VM36 ReactPerfDevtool.js:1)
    at t.updateMeasures (VM36 ReactPerfDevtool.js:1)
    at VM36 ReactPerfDevtool.js:1
    at callbackWrapper (<anonymous>:53:1)
    at ExtensionServerClient._onCallback (<anonymous>:66:653)
    at ExtensionServerClient._onMessage (<anonymous>:67:9)
```

**Comment by srinivas640** [comment]
hi is this issue fixed , i see same issue with unknown type we use react,redux with providers.

**Comment by nitin42** [comment]
Released a new update version `5.2`. Should fix this!

**Comment by jaebradley** [comment]
@nitin42 I'm still running into this (or a similar error)

![image](https://user-images.githubusercontent.com/8136030/44444979-29cf6280-a594-11e8-876c-1ffb13757286.png)

![image](https://user-images.githubusercontent.com/8136030/44444931-ff7da500-a593-11e8-8721-181f29017f30.png)

![image](https://user-images.githubusercontent.com/8136030/44444942-073d4980-a594-11e8-9343-b088a6747012.png)

Let me know if you need any more debug information.

**Comment by nitin42** [comment]
Thanks for reporting the issue. I can confirm it was a chart.js issue. I have released a new version of extension (`5.4`) which hopefully fixes this issue. I have tested the build on two of my projects and everything seems to be working fine.

**Comment by jaebradley** [comment]
@nitin42 I'm on `5.4` and I'm still seeing this error. To make sure it wasn't any other extensions, I loaded my application in a relatively "fresh" state - I'm using Chrome Canary with React DevTools, Redux DevTools, and React Performance DevTools.

### `v5.4`
![image](https://user-images.githubusercontent.com/8136030/44476376-662ead00-a5ec-11e8-993c-c48e6fde6d9e.png)

### Chrome Canary Information
![image](https://user-images.githubusercontent.com/8136030/44476401-79da1380-a5ec-11e8-90df-10088ae537c0.png)

### `react` and `react-dom` versions
![image](https://user-images.githubusercontent.com/8136030/44476449-9a09d280-a5ec-11e8-9b51-665728544ee4.png)
![image](https://user-images.githubusercontent.com/8136030/44476456-a130e080-a5ec-11e8-844e-46c4bbe1d1bc.png)

### Have access to `window.__REACT_PERF_DEVTOOL_GLOBAL_STORE__`

Unsurprisingly, I have access to `window.__REACT_PERF_DEVTOOL_GLOBAL_STORE__`

![image](https://user-images.githubusercontent.com/8136030/44476577-13092a00-a5ed-11e8-824d-7297f05a4bd8.png)

### Error
![image](https://user-images.githubusercontent.com/8136030/44476480-b3ab1a00-a5ec-11e8-9454-4c45184f9d8c.png)

I noticed that #39 is related to `create-react-app`. I'm using `create-react-app` as well - I don't know if this is coincidence, or if there's something behind these errors.

**Comment by nitin42** [comment]
Can you show me a screenshot of codebase where you are using `registerObserver` ?

**Comment by jaebradley** [comment]
No I can't unfortunately - I am calling `registerObserver` in my top-level Application component. Whether `registerObserver` is invoked before or after the component's render method does not seem to change the effect.

**Comment by nitin42** [comment]
Looking at #39, I was able to resolve it by placing the function call (`registerObserver`) before `ReactDOM.render`.

**Comment by nitin42** [comment]
`registerObserver` needs to be hoisted before `RDOM.render` because otherwise it won't be able to infer the React components present in your project directory.

**Comment by nitin42** [comment]
Hey @jaebradley, I found the fix for your problem. Keep an eye on this repo. I'll be releasing a new version of observer and tool soon

**Comment by nitin42** [comment]
This issue is mainly due to initialisation process of the extension. The extension loads before your application, and hence you end up in error state. I've released a new version of the observer hook with which you can defer the initialisation process with a timeout value.

In the earlier version of the developer tool, the default timeout value was `2000`. Try increasing the timeout value and see if it works.

The extension is also updated with the version `5.5`

Install the new observer hook beta with

```
yarn add react-perf-devtool@3.1.8-beta.2
```
Configure the timeout value like this -

```js
registerObserver({ timeout: desire_value_in_number })
```
Let me know if it works and then I'll go ahead and update the docs.
